project:
  type: website

execute:
  freeze: auto

website:
  title: "A bioinfo blog by Luca Gaessler"
  navbar:
    right:
      - icon: github
        href: github.com/lucagaessler/BioInfo_Blog_LG
      - icon: linkedin
        href: www.linkedin.com/in/luca-gaessler/
format:
  html:
    theme: 
      - darkly
    css: styles.css



