project:
  type: website

execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  title: "Bioinfo Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      - flatly
    css: styles.css



