project:
  type: website

execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  title: "Bioinfo Blog"
  navbar:
    right:
      - icon: github
        href: https://https://github.com/lucagaessler/BioInfo_Blog_LG
      - icon: linkedin
        href: https://https://www.linkedin.com/in/luca-gaessler/
format:
  html:
    theme: 
      - darkly
    css: styles.css



